import { PokemonFormType } from "./types";

// Hardcoded Pokemon categorization based on manual review
// This takes priority over pattern detection for accurate results
export const hardcodedPokemonCategories: Record<string, PokemonFormType> = {
  // Normal Pokemon (IDs 1-1025 and some special cases)
  "bulbasaur": "normal",
  "ivysaur": "normal",
  "venusaur": "normal",
  "charmander": "normal",
  "charmeleon": "normal",
  "charizard": "normal",
  "squirtle": "normal",
  "wartortle": "normal",
  "blastoise": "normal",
  "caterpie": "normal",
  "metapod": "normal",
  "butterfree": "normal",
  "weedle": "normal",
  "kakuna": "normal",
  "beedrill": "normal",
  "pidgey": "normal",
  "pidgeotto": "normal",
  "pidgeot": "normal",
  "rattata": "normal",
  "raticate": "normal",
  "spearow": "normal",
  "fearow": "normal",
  "ekans": "normal",
  "arbok": "normal",
  "pikachu": "normal",
  "raichu": "normal",
  "sandshrew": "normal",
  "sandslash": "normal",
  "nidoran-f": "normal",
  "nidorina": "normal",
  "nidoqueen": "normal",
  "nidoran-m": "normal",
  "nidorino": "normal",
  "nidoking": "normal",
  "clefairy": "normal",
  "clefable": "normal",
  "vulpix": "normal",
  "ninetales": "normal",
  "jigglypuff": "normal",
  "wigglytuff": "normal",
  "zubat": "normal",
  "golbat": "normal",
  "oddish": "normal",
  "gloom": "normal",
  "vileplume": "normal",
  "paras": "normal",
  "parasect": "normal",
  "venonat": "normal",
  "venomoth": "normal",
  "diglett": "normal",
  "dugtrio": "normal",
  "meowth": "normal",
  "persian": "normal",
  "psyduck": "normal",
  "golduck": "normal",
  "mankey": "normal",
  "primeape": "normal",
  "growlithe": "normal",
  "arcanine": "normal",
  "poliwag": "normal",
  "poliwhirl": "normal",
  "poliwrath": "normal",
  "abra": "normal",
  "kadabra": "normal",
  "alakazam": "normal",
  "machop": "normal",
  "machoke": "normal",
  "machamp": "normal",
  "bellsprout": "normal",
  "weepinbell": "normal",
  "victreebel": "normal",
  "tentacool": "normal",
  "tentacruel": "normal",
  "geodude": "normal",
  "graveler": "normal",
  "golem": "normal",
  "ponyta": "normal",
  "rapidash": "normal",
  "slowpoke": "normal",
  "slowbro": "normal",
  "magnemite": "normal",
  "magneton": "normal",
  "farfetchd": "normal",
  "doduo": "normal",
  "dodrio": "normal",
  "seel": "normal",
  "dewgong": "normal",
  "grimer": "normal",
  "muk": "normal",
  "shellder": "normal",
  "cloyster": "normal",
  "gastly": "normal",
  "haunter": "normal",
  "gengar": "normal",
  "onix": "normal",
  "drowzee": "normal",
  "hypno": "normal",
  "krabby": "normal",
  "kingler": "normal",
  "voltorb": "normal",
  "electrode": "normal",
  "exeggcute": "normal",
  "exeggutor": "normal",
  "cubone": "normal",
  "marowak": "normal",
  "hitmonlee": "normal",
  "hitmonchan": "normal",
  "lickitung": "normal",
  "koffing": "normal",
  "weezing": "normal",
  "rhyhorn": "normal",
  "rhydon": "normal",
  "chansey": "normal",
  "tangela": "normal",
  "kangaskhan": "normal",
  "horsea": "normal",
  "seadra": "normal",
  "goldeen": "normal",
  "seaking": "normal",
  "staryu": "normal",
  "starmie": "normal",
  "mr-mime": "normal",
  "scyther": "normal",
  "jynx": "normal",
  "electabuzz": "normal",
  "magmar": "normal",
  "pinsir": "normal",
  "tauros": "normal",
  "magikarp": "normal",
  "gyarados": "normal",
  "lapras": "normal",
  "ditto": "normal",
  "eevee": "normal",
  "vaporeon": "normal",
  "jolteon": "normal",
  "flareon": "normal",
  "porygon": "normal",
  "omanyte": "normal",
  "omastar": "normal",
  "kabuto": "normal",
  "kabutops": "normal",
  "aerodactyl": "normal",
  "snorlax": "normal",
  "articuno": "normal",
  "zapdos": "normal",
  "moltres": "normal",
  "dratini": "normal",
  "dragonair": "normal",
  "dragonite": "normal",
  "mewtwo": "normal",
  "mew": "normal",

  // ADD ALL MISSING NORMAL POKEMON FROM GENERATIONS 2-9 (IDs 152-1025)
  // Generation 2
  "chikorita": "normal", "bayleef": "normal", "meganium": "normal", "cyndaquil": "normal", "quilava": "normal", "typhlosion": "normal", "totodile": "normal", "croconaw": "normal", "feraligatr": "normal", "sentret": "normal", "furret": "normal", "hoothoot": "normal", "noctowl": "normal", "ledyba": "normal", "ledian": "normal", "spinarak": "normal", "ariados": "normal", "crobat": "normal", "chinchou": "normal", "lanturn": "normal", "pichu": "normal", "cleffa": "normal", "igglybuff": "normal", "togepi": "normal", "togetic": "normal", "natu": "normal", "xatu": "normal", "mareep": "normal", "flaaffy": "normal", "ampharos": "normal", "bellossom": "normal", "marill": "normal", "azumarill": "normal", "sudowoodo": "normal", "politoed": "normal", "hoppip": "normal", "skiploom": "normal", "jumpluff": "normal", "aipom": "normal", "sunkern": "normal", "sunflora": "normal", "yanma": "normal", "wooper": "normal", "quagsire": "normal", "espeon": "normal", "umbreon": "normal", "murkrow": "normal", "slowking": "normal", "misdreavus": "normal", "unown": "normal", "wobbuffet": "normal", "girafarig": "normal", "pineco": "normal", "forretress": "normal", "dunsparce": "normal", "gligar": "normal", "steelix": "normal", "snubbull": "normal", "granbull": "normal", "qwilfish": "normal", "scizor": "normal", "shuckle": "normal", "heracross": "normal", "sneasel": "normal", "teddiursa": "normal", "ursaring": "normal", "slugma": "normal", "magcargo": "normal", "swinub": "normal", "piloswine": "normal", "corsola": "normal", "remoraid": "normal", "octillery": "normal", "delibird": "normal", "mantine": "normal", "skarmory": "normal", "houndour": "normal", "houndoom": "normal", "kingdra": "normal", "phanpy": "normal", "donphan": "normal", "porygon2": "normal", "stantler": "normal", "smeargle": "normal", "tyrogue": "normal", "hitmontop": "normal", "smoochum": "normal", "elekid": "normal", "magby": "normal", "miltank": "normal", "blissey": "normal", "raikou": "normal", "entei": "normal", "suicune": "normal", "larvitar": "normal", "pupitar": "normal", "tyranitar": "normal", "lugia": "normal", "ho-oh": "normal", "celebi": "normal",

  // Generation 3
  "treecko": "normal", "grovyle": "normal", "sceptile": "normal", "torchic": "normal", "combusken": "normal", "blaziken": "normal", "mudkip": "normal", "marshtomp": "normal", "swampert": "normal", "poochyena": "normal", "mightyena": "normal", "zigzagoon": "normal", "linoone": "normal", "wurmple": "normal", "silcoon": "normal", "beautifly": "normal", "cascoon": "normal", "dustox": "normal", "lotad": "normal", "lombre": "normal", "ludicolo": "normal", "seedot": "normal", "nuzleaf": "normal", "shiftry": "normal", "taillow": "normal", "swellow": "normal", "wingull": "normal", "pelipper": "normal", "ralts": "normal", "kirlia": "normal", "gardevoir": "normal", "surskit": "normal", "masquerain": "normal", "shroomish": "normal", "breloom": "normal", "slakoth": "normal", "vigoroth": "normal", "slaking": "normal", "nincada": "normal", "ninjask": "normal", "shedinja": "normal", "whismur": "normal", "loudred": "normal", "exploud": "normal", "makuhita": "normal", "hariyama": "normal", "azurill": "normal", "nosepass": "normal", "skitty": "normal", "delcatty": "normal", "sableye": "normal", "mawile": "normal", "aron": "normal", "lairon": "normal", "aggron": "normal", "meditite": "normal", "medicham": "normal", "electrike": "normal", "manectric": "normal", "plusle": "normal", "minun": "normal", "volbeat": "normal", "illumise": "normal", "roselia": "normal", "gulpin": "normal", "swalot": "normal", "carvanha": "normal", "sharpedo": "normal", "wailmer": "normal", "wailord": "normal", "numel": "normal", "camerupt": "normal", "torkoal": "normal", "spoink": "normal", "grumpig": "normal", "spinda": "normal", "trapinch": "normal", "vibrava": "normal", "flygon": "normal", "cacnea": "normal", "cacturne": "normal", "swablu": "normal", "altaria": "normal", "zangoose": "normal", "seviper": "normal", "lunatone": "normal", "solrock": "normal", "barboach": "normal", "whiscash": "normal", "corphish": "normal", "crawdaunt": "normal", "baltoy": "normal", "claydol": "normal", "lileep": "normal", "cradily": "normal", "anorith": "normal", "armaldo": "normal", "feebas": "normal", "milotic": "normal", "castform": "normal", "kecleon": "normal", "shuppet": "normal", "banette": "normal", "duskull": "normal", "dusclops": "normal", "tropius": "normal", "chimecho": "normal", "absol": "normal", "wynaut": "normal", "snorunt": "normal", "glalie": "normal", "spheal": "normal", "sealeo": "normal", "walrein": "normal", "clamperl": "normal", "huntail": "normal", "gorebyss": "normal", "relicanth": "normal", "luvdisc": "normal", "bagon": "normal", "shelgon": "normal", "salamence": "normal", "beldum": "normal", "metang": "normal", "metagross": "normal", "regirock": "normal", "regice": "normal", "registeel": "normal", "latias": "normal", "latios": "normal", "kyogre": "normal", "groudon": "normal", "rayquaza": "normal", "jirachi": "normal", "deoxys": "normal",

  // Generation 4 
  "turtwig": "normal", "grotle": "normal", "torterra": "normal", "chimchar": "normal", "monferno": "normal", "infernape": "normal", "piplup": "normal", "prinplup": "normal", "empoleon": "normal", "starly": "normal", "staravia": "normal", "staraptor": "normal", "bidoof": "normal", "bibarel": "normal", "kricketot": "normal", "kricketune": "normal", "shinx": "normal", "luxio": "normal", "luxray": "normal", "budew": "normal", "roserade": "normal", "cranidos": "normal", "rampardos": "normal", "shieldon": "normal", "bastiodon": "normal", "burmy": "normal", "wormadam": "normal", "mothim": "normal", "combee": "normal", "vespiquen": "normal", "pachirisu": "normal", "buizel": "normal", "floatzel": "normal", "cherubi": "normal", "cherrim": "normal", "shellos": "normal", "gastrodon": "normal", "ambipom": "normal", "drifloon": "normal", "drifblim": "normal", "buneary": "normal", "lopunny": "normal", "mismagius": "normal", "honchkrow": "normal", "glameow": "normal", "purugly": "normal", "chingling": "normal", "stunky": "normal", "skuntank": "normal", "bronzor": "normal", "bronzong": "normal", "bonsly": "normal", "mime-jr": "normal", "happiny": "normal", "chatot": "normal", "spiritomb": "normal", "gible": "normal", "gabite": "normal", "garchomp": "normal", "munchlax": "normal", "riolu": "normal", "lucario": "normal", "hippopotas": "normal", "hippowdon": "normal", "skorupi": "normal", "drapion": "normal", "croagunk": "normal", "toxicroak": "normal", "carnivine": "normal", "finneon": "normal", "lumineon": "normal", "mantyke": "normal", "snover": "normal", "abomasnow": "normal", "weavile": "normal", "magnezone": "normal", "lickilicky": "normal", "rhyperior": "normal", "tangrowth": "normal", "electivire": "normal", "magmortar": "normal", "togekiss": "normal", "yanmega": "normal", "leafeon": "normal", "glaceon": "normal", "gliscor": "normal", "mamoswine": "normal", "porygon-z": "normal", "gallade": "normal", "probopass": "normal", "dusknoir": "normal", "froslass": "normal", "rotom": "normal", "uxie": "normal", "mesprit": "normal", "azelf": "normal", "dialga": "normal", "palkia": "normal", "heatran": "normal", "regigigas": "normal", "giratina": "normal", "cresselia": "normal", "phione": "normal", "manaphy": "normal", "darkrai": "normal", "shaymin": "normal", "arceus": "normal",

  // Generation 5
  "victini": "normal", "snivy": "normal", "servine": "normal", "serperior": "normal", "tepig": "normal", "pignite": "normal", "emboar": "normal", "oshawott": "normal", "dewott": "normal", "samurott": "normal", "patrat": "normal", "watchog": "normal", "lillipup": "normal", "herdier": "normal", "stoutland": "normal", "purrloin": "normal", "liepard": "normal", "pansage": "normal", "simisage": "normal", "pansear": "normal", "simisear": "normal", "panpour": "normal", "simipour": "normal", "munna": "normal", "musharna": "normal", "pidove": "normal", "tranquill": "normal", "unfezant": "normal", "blitzle": "normal", "zebstrika": "normal", "roggenrola": "normal", "boldore": "normal", "gigalith": "normal", "woobat": "normal", "swoobat": "normal", "drilbur": "normal", "excadrill": "normal", "audino": "normal", "timburr": "normal", "gurdurr": "normal", "conkeldurr": "normal", "tympole": "normal", "palpitoad": "normal", "seismitoad": "normal", "throh": "normal", "sawk": "normal", "sewaddle": "normal", "swadloon": "normal", "leavanny": "normal", "venipede": "normal", "whirlipede": "normal", "scolipede": "normal", "cottonee": "normal", "whimsicott": "normal", "petilil": "normal", "lilligant": "normal", "basculin": "normal", "sandile": "normal", "krokorok": "normal", "krookodile": "normal", "darumaka": "normal", "darmanitan": "normal", "maractus": "normal", "dwebble": "normal", "crustle": "normal", "scraggy": "normal", "scrafty": "normal", "sigilyph": "normal", "yamask": "normal", "cofagrigus": "normal", "tirtouga": "normal", "carracosta": "normal", "archen": "normal", "archeops": "normal", "trubbish": "normal", "garbodor": "normal", "zorua": "normal", "zoroark": "normal", "minccino": "normal", "cinccino": "normal", "gothita": "normal", "gothorita": "normal", "gothitelle": "normal", "solosis": "normal", "duosion": "normal", "reuniclus": "normal", "ducklett": "normal", "swanna": "normal", "vanillite": "normal", "vanillish": "normal", "vanilluxe": "normal", "deerling": "normal", "sawsbuck": "normal", "emolga": "normal", "karrablast": "normal", "escavalier": "normal", "foongus": "normal", "amoonguss": "normal", "frillish": "normal", "jellicent": "normal", "alomomola": "normal", "joltik": "normal", "galvantula": "normal", "ferroseed": "normal", "ferrothorn": "normal", "klink": "normal", "klang": "normal", "klinklang": "normal", "tynamo": "normal", "eelektrik": "normal", "eelektross": "normal", "elgyem": "normal", "beheeyem": "normal", "litwick": "normal", "lampent": "normal", "chandelure": "normal", "axew": "normal", "fraxure": "normal", "haxorus": "normal", "cubchoo": "normal", "beartic": "normal", "cryogonal": "normal", "shelmet": "normal", "accelgor": "normal", "stunfisk": "normal", "mienfoo": "normal", "mienshao": "normal", "druddigon": "normal", "golett": "normal", "golurk": "normal", "pawniard": "normal", "bisharp": "normal", "bouffalant": "normal", "rufflet": "normal", "braviary": "normal", "vullaby": "normal", "mandibuzz": "normal", "heatmor": "normal", "durant": "normal", "deino": "normal", "zweilous": "normal", "hydreigon": "normal", "larvesta": "normal", "volcarona": "normal", "cobalion": "normal", "terrakion": "normal", "virizion": "normal", "tornadus": "normal", "thundurus": "normal", "reshiram": "normal", "zekrom": "normal", "landorus": "normal", "kyurem": "normal", "keldeo": "normal", "meloetta": "normal", "genesect": "normal",

  // Generation 6
  "chespin": "normal", "quilladin": "normal", "chesnaught": "normal", "fennekin": "normal", "braixen": "normal", "delphox": "normal", "froakie": "normal", "frogadier": "normal", "greninja": "normal", "bunnelby": "normal", "diggersby": "normal", "fletchling": "normal", "fletchinder": "normal", "talonflame": "normal", "scatterbug": "normal", "spewpa": "normal", "vivillon": "normal", "litleo": "normal", "pyroar": "normal", "flabebe": "normal", "floette": "normal", "florges": "normal", "skiddo": "normal", "gogoat": "normal", "pancham": "normal", "pangoro": "normal", "furfrou": "normal", "espurr": "normal", "meowstic": "normal", "honedge": "normal", "doublade": "normal", "aegislash": "normal", "spritzee": "normal", "aromatisse": "normal", "swirlix": "normal", "slurpuff": "normal", "inkay": "normal", "malamar": "normal", "binacle": "normal", "barbaracle": "normal", "skrelp": "normal", "dragalge": "normal", "clauncher": "normal", "clawitzer": "normal", "helioptile": "normal", "heliolisk": "normal", "tyrunt": "normal", "tyrantrum": "normal", "amaura": "normal", "aurorus": "normal", "sylveon": "normal", "hawlucha": "normal", "dedenne": "normal", "carbink": "normal", "goomy": "normal", "sliggoo": "normal", "goodra": "normal", "klefki": "normal", "phantump": "normal", "trevenant": "normal", "pumpkaboo": "normal", "gourgeist": "normal", "bergmite": "normal", "avalugg": "normal", "noibat": "normal", "noivern": "normal", "xerneas": "normal", "yveltal": "normal", "zygarde": "normal", "diancie": "normal", "hoopa": "normal", "volcanion": "normal",

  // Generation 7
  "rowlet": "normal", "dartrix": "normal", "decidueye": "normal", "litten": "normal", "torracat": "normal", "incineroar": "normal", "popplio": "normal", "brionne": "normal", "primarina": "normal", "pikipek": "normal", "trumbeak": "normal", "toucannon": "normal", "yungoos": "normal", "gumshoos": "normal", "grubbin": "normal", "charjabug": "normal", "vikavolt": "normal", "crabrawler": "normal", "crabominable": "normal", "oricorio": "normal", "cutiefly": "normal", "ribombee": "normal", "rockruff": "normal", "lycanroc": "normal", "wishiwashi": "normal", "mareanie": "normal", "toxapex": "normal", "mudbray": "normal", "mudsdale": "normal", "dewpider": "normal", "araquanid": "normal", "fomantis": "normal", "lurantis": "normal", "morelull": "normal", "shiinotic": "normal", "salandit": "normal", "salazzle": "normal", "stufful": "normal", "bewear": "normal", "bounsweet": "normal", "steenee": "normal", "tsareena": "normal", "comfey": "normal", "oranguru": "normal", "passimian": "normal", "wimpod": "normal", "golisopod": "normal", "sandygast": "normal", "palossand": "normal", "pyukumuku": "normal", "type-null": "normal", "silvally": "normal", "minior": "normal", "komala": "normal", "turtonator": "normal", "togedemaru": "normal", "mimikyu": "normal", "bruxish": "normal", "drampa": "normal", "dhelmise": "normal", "jangmo-o": "normal", "hakamo-o": "normal", "kommo-o": "normal", "tapu-koko": "normal", "tapu-lele": "normal", "tapu-bulu": "normal", "tapu-fini": "normal", "cosmog": "normal", "cosmoem": "normal", "solgaleo": "normal", "lunala": "normal", "necrozma": "normal", "magearna": "normal", "marshadow": "normal", "poipole": "normal", "naganadel": "normal", "stakataka": "normal", "blacephalon": "normal", "zeraora": "normal", "meltan": "normal", "melmetal": "normal",

  // Generation 8 
  "grookey": "normal", "thwackey": "normal", "rillaboom": "normal", "scorbunny": "normal", "raboot": "normal", "cinderace": "normal", "sobble": "normal", "drizzile": "normal", "inteleon": "normal", "skwovet": "normal", "greedent": "normal", "rookidee": "normal", "corvisquire": "normal", "corviknight": "normal", "blipbug": "normal", "dottler": "normal", "orbeetle": "normal", "nickit": "normal", "thievul": "normal", "gossifleur": "normal", "eldegoss": "normal", "wooloo": "normal", "dubwool": "normal", "chewtle": "normal", "drednaw": "normal", "yamper": "normal", "boltund": "normal", "rolycoly": "normal", "carkol": "normal", "coalossal": "normal", "applin": "normal", "flapple": "normal", "appletun": "normal", "silicobra": "normal", "sandaconda": "normal", "cramorant": "normal", "arrokuda": "normal", "barraskewda": "normal", "toxel": "normal", "toxtricity": "normal", "sizzlipede": "normal", "centiskorch": "normal", "clobbopus": "normal", "grapploct": "normal", "sinistea": "normal", "polteageist": "normal", "hatenna": "normal", "hattrem": "normal", "hatterene": "normal", "impidimp": "normal", "morgrem": "normal", "grimmsnarl": "normal", "obstagoon": "normal", "perrserker": "normal", "cursola": "normal", "sirfetchd": "normal", "mr-rime": "normal", "runerigus": "normal", "milcery": "normal", "alcremie": "normal", "falinks": "normal", "pincurchin": "normal", "snom": "normal", "frosmoth": "normal", "stonjourner": "normal", "eiscue": "normal", "indeedee": "normal", "morpeko": "normal", "cufant": "normal", "copperajah": "normal", "dracozolt": "normal", "arctozolt": "normal", "dracovish": "normal", "arctovish": "normal", "duraludon": "normal", "dreepy": "normal", "drakloak": "normal", "dragapult": "normal", "zacian": "normal", "zamazenta": "normal", "eternatus": "normal", "kubfu": "normal", "urshifu": "normal", "zarude": "normal", "regieleki": "normal", "regidrago": "normal", "glastrier": "normal", "spectrier": "normal", "calyrex": "normal",

  // Generation 9
  "sprigatito": "normal", "floragato": "normal", "meowscarada": "normal", "fuecoco": "normal", "crocalor": "normal", "skeledirge": "normal", "quaxly": "normal", "quaxwell": "normal", "quaquaval": "normal", "lechonk": "normal", "oinkologne": "normal", "tarountula": "normal", "spidops": "normal", "nymble": "normal", "lokix": "normal", "pawmi": "normal", "pawmo": "normal", "pawmot": "normal", "tandemaus": "normal", "maushold": "normal", "fidough": "normal", "dachsbun": "normal", "smoliv": "normal", "dolliv": "normal", "arboliva": "normal", "squawkabilly": "normal", "nacli": "normal", "naclstack": "normal", "garganacl": "normal", "charcadet": "normal", "armarouge": "normal", "ceruledge": "normal", "tadbulb": "normal", "bellibolt": "normal", "wattrel": "normal", "kilowattrel": "normal", "maschiff": "normal", "mabosstiff": "normal", "shroodle": "normal", "grafaiai": "normal", "bramblin": "normal", "brambleghast": "normal", "toedscool": "normal", "toedscruel": "normal", "klawf": "normal", "capsakid": "normal", "scovillain": "normal", "rellor": "normal", "rabsca": "normal", "flittle": "normal", "espathra": "normal", "tinkatink": "normal", "tinkaton": "normal", "wiglett": "normal", "wugtrio": "normal", "bombirdier": "normal", "finizen": "normal", "palafin": "normal", "varoom": "normal", "revavroom": "normal", "cyclizar": "normal", "orthworm": "normal", "glimmet": "normal", "glimmora": "normal", "greavard": "normal", "houndstone": "normal", "flamigo": "normal", "cetoddle": "normal", "cetitan": "normal", "veluza": "normal", "dondozo": "normal", "tatsugiri": "normal", "annihilape": "normal", "clodsire": "normal", "farigiraf": "normal", "dudunsparce": "normal", "kingambit": "normal", "great-tusk": "normal", "scream-tail": "normal", "brute-bonnet": "normal", "flutter-mane": "normal", "slither-wing": "normal", "sandy-shocks": "normal", "iron-treads": "normal", "iron-bundle": "normal", "iron-hands": "normal", "iron-jugulis": "normal", "iron-moth": "normal", "iron-thorns": "normal", "frigibax": "normal", "arctibax": "normal", "baxcalibur": "normal", "gimmighoul": "normal", "gholdengo": "normal", "wo-chien": "normal", "chien-pao": "normal", "ting-lu": "normal", "chi-yu": "normal", "roaring-moon": "normal", "iron-valiant": "normal", "koraidon": "normal", "miraidon": "normal", "walking-wake": "normal", "iron-leaves": "normal", "dipplin": "normal", "poltchageist": "normal", "sinistcha": "normal", "okidogi": "normal", "munkidori": "normal", "fezandipiti": "normal", "ogerpon": "normal", "archaludon": "normal", "hydrapple": "normal", "gouging-fire": "normal", "raging-bolt": "normal", "iron-boulder": "normal", "iron-crown": "normal", "terapagos": "normal", "pecharunt": "normal",

  // Regional variants
  "terapagos-stellar": "forms",
  "ogerpon-cornerstone-mask": "forms",
  "palkia-origin": "originPrimal",
  "toxtricity-low-key-gmax": "megaGmax",
  "pikachu-world-cap": "costumes",
  "wooper-paldea": "regional",
  "enamorus-therian": "forms",
  "squawkabilly-white-plumage": "colorsFlavors",

  // Mega/Gmax forms
  "venusaur-mega": "megaGmax",
  "charizard-mega-x": "megaGmax",
  "charizard-mega-y": "megaGmax",
  "blastoise-mega": "megaGmax",
  "alakazam-mega": "megaGmax",
  "gengar-mega": "megaGmax",
  "kangaskhan-mega": "megaGmax",
  "pinsir-mega": "megaGmax",
  "gyarados-mega": "megaGmax",
  "aerodactyl-mega": "megaGmax",
  "mewtwo-mega-x": "megaGmax",
  "mewtwo-mega-y": "megaGmax",
  "ampharos-mega": "megaGmax",
  "scizor-mega": "megaGmax",
  "heracross-mega": "megaGmax",
  "houndoom-mega": "megaGmax",
  "tyranitar-mega": "megaGmax",
  "blaziken-mega": "megaGmax",
  "gardevoir-mega": "megaGmax",
  "mawile-mega": "megaGmax",
  "aggron-mega": "megaGmax",
  "medicham-mega": "megaGmax",
  "manectric-mega": "megaGmax",
  "banette-mega": "megaGmax",
  "absol-mega": "megaGmax",
  "garchomp-mega": "megaGmax",
  "lucario-mega": "megaGmax",
  "abomasnow-mega": "megaGmax",
  "latias-mega": "megaGmax",
  "latios-mega": "megaGmax",
  "swampert-mega": "megaGmax",
  "sceptile-mega": "megaGmax",
  "sableye-mega": "megaGmax",
  "altaria-mega": "megaGmax",
  "gallade-mega": "megaGmax",
  "audino-mega": "megaGmax",
  "sharpedo-mega": "megaGmax",
  "slowbro-mega": "megaGmax",
  "steelix-mega": "megaGmax",
  "pidgeot-mega": "megaGmax",
  "glalie-mega": "megaGmax",
  "diancie-mega": "megaGmax",
  "metagross-mega": "megaGmax",
  "rayquaza-mega": "megaGmax",
  "camerupt-mega": "megaGmax",
  "lopunny-mega": "megaGmax",
  "salamence-mega": "megaGmax",
  "beedrill-mega": "megaGmax",
  "eternatus-eternamax": "megaGmax",

  // Gmax forms
  "venusaur-gmax": "megaGmax",
  "charizard-gmax": "megaGmax",
  "blastoise-gmax": "megaGmax",
  "butterfree-gmax": "megaGmax",
  "pikachu-gmax": "megaGmax",
  "meowth-gmax": "megaGmax",
  "machamp-gmax": "megaGmax",
  "gengar-gmax": "megaGmax",
  "kingler-gmax": "megaGmax",
  "lapras-gmax": "megaGmax",
  "eevee-gmax": "megaGmax",
  "snorlax-gmax": "megaGmax",
  "garbodor-gmax": "megaGmax",
  "melmetal-gmax": "megaGmax",
  "rillaboom-gmax": "megaGmax",
  "cinderace-gmax": "megaGmax",
  "inteleon-gmax": "megaGmax",
  "corviknight-gmax": "megaGmax",
  "orbeetle-gmax": "megaGmax",
  "drednaw-gmax": "megaGmax",
  "coalossal-gmax": "megaGmax",
  "flapple-gmax": "megaGmax",
  "appletun-gmax": "megaGmax",
  "sandaconda-gmax": "megaGmax",
  "toxtricity-amped-gmax": "megaGmax",
  "centiskorch-gmax": "megaGmax",
  "hatterene-gmax": "megaGmax",
  "grimmsnarl-gmax": "megaGmax",
  "alcremie-gmax": "megaGmax",
  "copperajah-gmax": "megaGmax",
  "duraludon-gmax": "megaGmax",
  "urshifu-single-strike-gmax": "megaGmax",
  "urshifu-rapid-strike-gmax": "megaGmax",

  // Origin/Primal forms
  "kyogre-primal": "originPrimal",
  "groudon-primal": "originPrimal",
  "giratina-origin": "originPrimal",
  "dialga-origin": "originPrimal",

  // Regional variants
  "rattata-alola": "regional",
  "raticate-alola": "regional",
  "raichu-alola": "regional",
  "sandshrew-alola": "regional",
  "sandslash-alola": "regional",
  "vulpix-alola": "regional",
  "ninetales-alola": "regional",
  "diglett-alola": "regional",
  "dugtrio-alola": "regional",
  "meowth-alola": "regional",
  "persian-alola": "regional",
  "geodude-alola": "regional",
  "graveler-alola": "regional",
  "golem-alola": "regional",
  "grimer-alola": "regional",
  "muk-alola": "regional",
  "exeggutor-alola": "regional",
  "marowak-alola": "regional",

  // Galarian forms
  "meowth-galar": "regional",
  "ponyta-galar": "regional",
  "rapidash-galar": "regional",
  "slowpoke-galar": "regional",
  "slowbro-galar": "regional",
  "farfetchd-galar": "regional",
  "weezing-galar": "regional",
  "mr-mime-galar": "regional",
  "articuno-galar": "regional",
  "zapdos-galar": "regional",
  "moltres-galar": "regional",
  "slowking-galar": "regional",
  "corsola-galar": "regional",
  "zigzagoon-galar": "regional",
  "linoone-galar": "regional",
  "darumaka-galar": "regional",
  "darmanitan-galar-standard": "regional",
  "yamask-galar": "regional",
  "stunfisk-galar": "regional",

  // Hisuian forms
  "growlithe-hisui": "regional",
  "arcanine-hisui": "regional",
  "voltorb-hisui": "regional",
  "electrode-hisui": "regional",
  "typhlosion-hisui": "regional",
  "qwilfish-hisui": "regional",
  "sneasel-hisui": "regional",
  "samurott-hisui": "regional",
  "lilligant-hisui": "regional",
  "zorua-hisui": "regional",
  "zoroark-hisui": "regional",
  "braviary-hisui": "regional",
  "sliggoo-hisui": "regional",
  "goodra-hisui": "regional",
  "avalugg-hisui": "regional",
  "decidueye-hisui": "regional",

  // Paldean forms
  "tauros-paldea-combat-breed": "forms",
  "tauros-paldea-blaze-breed": "forms",
  "tauros-paldea-aqua-breed": "forms",

  // Costume Pokemon
  "pikachu-rock-star": "costumes",
  "pikachu-belle": "costumes",
  "pikachu-pop-star": "costumes",
  "pikachu-phd": "costumes",
  "pikachu-libre": "costumes",
  "pikachu-cosplay": "costumes",
  "pikachu-original-cap": "costumes",
  "pikachu-hoenn-cap": "costumes",
  "pikachu-sinnoh-cap": "costumes",
  "pikachu-unova-cap": "costumes",
  "pikachu-kalos-cap": "costumes",
  "pikachu-alola-cap": "costumes",
  "pikachu-partner-cap": "costumes",

  // Color/Flavor variants
  "basculin-blue-striped": "colorsFlavors",
  "basculin-white-striped": "colorsFlavors",
  "minior-red": "colorsFlavors",
  "minior-orange": "colorsFlavors",
  "minior-yellow": "colorsFlavors",
  "minior-green": "colorsFlavors",
  "minior-blue": "colorsFlavors",
  "minior-indigo": "colorsFlavors",
  "minior-violet": "colorsFlavors",
  "squawkabilly-blue-plumage": "colorsFlavors",
  "squawkabilly-yellow-plumage": "colorsFlavors",
  "squawkabilly-green-plumage": "normal",

  // Gender differences
  "meowstic-female": "gender",
  "indeedee-female": "gender",
  "basculegion-female": "gender",
  "oinkologne-female": "gender",

  // Special forms
  "deoxys-attack": "forms",
  "deoxys-defense": "forms",
  "deoxys-speed": "forms",
  "deoxys-normal": "normal",
  "wormadam-sandy": "forms",
  "wormadam-trash": "forms",
  "wormadam-plant": "normal",
  "shaymin-sky": "forms",
  "shaymin-land": "normal",
  "rotom-heat": "forms",
  "rotom-wash": "forms",
  "rotom-frost": "forms",
  "rotom-fan": "forms",
  "rotom-mow": "forms",
  "rotom": "normal",
  "castform-sunny": "forms",
  "castform-rainy": "forms",
  "castform-snowy": "forms",
  "castform": "normal",
  "darmanitan-zen": "forms",
  "meloetta-pirouette": "forms",
  "meloetta-aria": "normal",
  "tornadus-therian": "forms",
  "thundurus-therian": "forms",
  "landorus-therian": "forms",
  "kyurem-black": "forms",
  "kyurem-white": "forms",
  "kyurem": "normal",
  "keldeo-resolute": "forms",
  "keldeo-ordinary": "normal",
  "aegislash-blade": "forms",
  "aegislash-shield": "normal",
  "floette-eternal": "forms",
  "hoopa-unbound": "forms",
  "hoopa": "normal",
  "greninja-battle-bond": "blocked",
  "greninja-ash": "forms",
  "greninja": "normal",
  "zygarde-10-power-construct": "forms",
  "zygarde-50-power-construct": "forms",
  "zygarde-complete": "forms",
  "zygarde-10": "forms",
  "zygarde-50": "normal",
  "oricorio-pom-pom": "forms",
  "oricorio-pau": "forms",
  "oricorio-sensu": "forms",
  "oricorio-baile": "normal",
  "lycanroc-midnight": "forms",
  "lycanroc-midday": "normal",
  "lycanroc-dusk": "forms",
  "wishiwashi-school": "forms",
  "wishiwashi-solo": "normal",
  "mimikyu-busted": "forms",
  "mimikyu-disguised": "normal",
  "necrozma-dusk": "forms",
  "necrozma-dawn": "forms",
  "necrozma-ultra": "forms",
  "necrozma": "normal",
  "darmanitan-galar-zen": "forms",
  "toxtricity-low-key": "forms",
  "toxtricity-amped": "normal",
  "eiscue-noice": "forms",
  "eiscue-ice": "normal",
  "morpeko-hangry": "forms",
  "morpeko-full-belly": "normal",
  "zacian-crowned": "forms",
  "zacian": "normal",
  "zamazenta-crowned": "forms",
  "zamazenta": "normal",
  "urshifu-rapid-strike": "forms",
  "urshifu-single-strike": "normal",
  "zarude-dada": "forms",
  "zarude": "normal",
  "calyrex-ice": "forms",
  "calyrex-shadow": "forms",
  "calyrex": "normal",
  "ursaluna-bloodmoon": "forms",
  "ogerpon-wellspring-mask": "forms",
  "ogerpon-hearthflame-mask": "forms",
  "ogerpon": "normal",
  "terapagos-terastal": "forms",
  "terapagos": "normal",
  "dudunsparce-three-segment": "forms",
  "dudunsparce-two-segment": "normal",
  "palafin-hero": "forms",
  "palafin-zero": "normal",
  "maushold-family-of-three": "forms",
  "maushold-family-of-four": "normal",
  "tatsugiri-droopy": "forms",
  "tatsugiri-stretchy": "forms",
  "tatsugiri-curly": "normal",
  "gimmighoul-roaming": "forms",
  "gimmighoul": "normal",
  "magearna-original": "forms",
  "magearna": "normal",

  // Blocked Pokemon (totem, size variants, special modes, etc.)
  "pumpkaboo-small": "blocked",
  "pumpkaboo-large": "blocked",
  "pumpkaboo-super": "blocked",
  "pumpkaboo-average": "normal",
  "gourgeist-small": "blocked",
  "gourgeist-large": "blocked",
  "gourgeist-super": "blocked",
  "gourgeist-average": "normal",
  "raticate-totem-alola": "blocked",
  "gumshoos-totem": "blocked",
  "vikavolt-totem": "blocked",
  "lurantis-totem": "blocked",
  "salazzle-totem": "blocked",
  "minior-orange-meteor": "blocked",
  "minior-yellow-meteor": "blocked",
  "minior-green-meteor": "blocked",
  "minior-blue-meteor": "blocked",
  "minior-indigo-meteor": "blocked",
  "minior-violet-meteor": "blocked",
  "minior-red-meteor": "normal",
  "mimikyu-totem-disguised": "blocked",
  "mimikyu-totem-busted": "blocked",
  "kommo-o-totem": "blocked",
  "marowak-totem": "blocked",
  "ribombee-totem": "blocked",
  "araquanid-totem": "blocked",
  "togedemaru-totem": "blocked",
  "pikachu-starter": "blocked",
  "eevee-starter": "blocked",
  "rockruff-own-tempo": "blocked",
  "cramorant-gulping": "blocked",
  "cramorant-gorging": "blocked",
  "cramorant": "normal",
  "koraidon-limited-build": "blocked",
  "koraidon-sprinting-build": "blocked",
  "koraidon-swimming-build": "blocked",
  "koraidon-gliding-build": "blocked",
  "koraidon": "normal",
  "miraidon-low-power-mode": "blocked",
  "miraidon-drive-mode": "blocked",
  "miraidon-aquatic-mode": "blocked",
  "miraidon-glide-mode": "blocked",
  "miraidon": "normal"
};

// Get all normal Pokemon IDs from 1-1025 for faster lookup
export const normalPokemonRange = new Set(Array.from({ length: 1025 }, (_, i) => i + 1));

export const getHardcodedCategory = (pokemonName: string): PokemonFormType | null => {
  const normalizedName = pokemonName.toLowerCase().trim();
  return hardcodedPokemonCategories[normalizedName] || null;
};
