
import { PokemonFormType } from "../types";

// Alternative forms, gender differences, costumes, colors/flavors
export const alternativeFormCategories: Record<string, PokemonFormType> = {
  // Costume Pokemon
  "pikachu-rock-star": "costumes",
  "pikachu-belle": "costumes",
  "pikachu-pop-star": "costumes",
  "pikachu-phd": "costumes",
  "pikachu-libre": "costumes",
  "pikachu-cosplay": "costumes",
  "pikachu-original-cap": "costumes",
  "pikachu-hoenn-cap": "costumes",
  "pikachu-sinnoh-cap": "costumes",
  "pikachu-unova-cap": "costumes",
  "pikachu-kalos-cap": "costumes",
  "pikachu-alola-cap": "costumes",
  "pikachu-partner-cap": "costumes",
  "pikachu-world-cap": "costumes",

  // Gender differences
  "meowstic-female": "gender",
  "indeedee-female": "gender",
  "basculegion-female": "gender",
  "oinkologne-female": "gender",

  // Color/Flavor variants
  "basculin-blue-striped": "colorsFlavors",
  "basculin-white-striped": "colorsFlavors",
  "minior-red": "colorsFlavors",
  "minior-orange": "colorsFlavors",
  "minior-yellow": "colorsFlavors",
  "minior-green": "colorsFlavors",
  "minior-blue": "colorsFlavors",
  "minior-indigo": "colorsFlavors",
  "minior-violet": "colorsFlavors",
  "squawkabilly-blue-plumage": "colorsFlavors",
  "squawkabilly-yellow-plumage": "colorsFlavors",
  "squawkabilly-white-plumage": "colorsFlavors",

  // Special forms
  "deoxys-attack": "forms",
  "deoxys-defense": "forms",
  "deoxys-speed": "forms",
  "wormadam-sandy": "forms",
  "wormadam-trash": "forms",
  "shaymin-sky": "forms",
  "rotom-heat": "forms",
  "rotom-wash": "forms",
  "rotom-frost": "forms",
  "rotom-fan": "forms",
  "rotom-mow": "forms",
  "castform-sunny": "forms",
  "castform-rainy": "forms",
  "castform-snowy": "forms",
  "darmanitan-zen": "forms",
  "meloetta-pirouette": "forms",
  "tornadus-therian": "forms",
  "thundurus-therian": "forms",
  "landorus-therian": "forms",
  "enamorus-therian": "forms",
  "kyurem-black": "forms",
  "kyurem-white": "forms",
  "keldeo-resolute": "forms",
  "aegislash-blade": "forms",
  "floette-eternal": "forms",
  "hoopa-unbound": "forms",
  "greninja-ash": "forms",
  "zygarde-10-power-construct": "forms",
  "zygarde-50-power-construct": "forms",
  "zygarde-complete": "forms",
  "zygarde-10": "forms",
  "oricorio-pom-pom": "forms",
  "oricorio-pau": "forms",
  "oricorio-sensu": "forms",
  "lycanroc-midnight": "forms",
  "lycanroc-dusk": "forms",
  "wishiwashi-school": "forms",
  "mimikyu-busted": "forms",
  "necrozma-dusk": "forms",
  "necrozma-dawn": "forms",
  "necrozma-ultra": "forms",
  "darmanitan-galar-zen": "forms",
  "toxtricity-low-key": "forms",
  "eiscue-noice": "forms",
  "morpeko-hangry": "forms",
  "zacian-crowned": "forms",
  "zamazenta-crowned": "forms",
  "urshifu-rapid-strike": "forms",
  "zarude-dada": "forms",
  "calyrex-ice": "forms",
  "calyrex-shadow": "forms",
  "ursaluna-bloodmoon": "forms",
  "ogerpon-wellspring-mask": "forms",
  "ogerpon-hearthflame-mask": "forms",
  "ogerpon-cornerstone-mask": "forms",
  "terapagos-terastal": "forms",
  "terapagos-stellar": "forms",
  "dudunsparce-three-segment": "forms",
  "palafin-hero": "forms",
  "maushold-family-of-three": "forms",
  "tatsugiri-droopy": "forms",
  "tatsugiri-stretchy": "forms",
  "gimmighoul-roaming": "forms",
  "magearna-original": "forms",
  "tauros-paldea-combat-breed": "forms",
  "tauros-paldea-blaze-breed": "forms",
  "tauros-paldea-aqua-breed": "forms"
};
