
import { PokemonFormType } from "../types";

// Mega, Gigantamax, Origin, Primal forms
export const specialFormCategories: Record<string, PokemonFormType> = {
  // Mega forms
  "venusaur-mega": "megaGmax",
  "charizard-mega-x": "megaGmax",
  "charizard-mega-y": "megaGmax",
  "blastoise-mega": "megaGmax",
  "alakazam-mega": "megaGmax",
  "gengar-mega": "megaGmax",
  "kangaskhan-mega": "megaGmax",
  "pinsir-mega": "megaGmax",
  "gyarados-mega": "megaGmax",
  "aerodactyl-mega": "megaGmax",
  "mewtwo-mega-x": "megaGmax",
  "mewtwo-mega-y": "megaGmax",
  "ampharos-mega": "megaGmax",
  "scizor-mega": "megaGmax",
  "heracross-mega": "megaGmax",
  "houndoom-mega": "megaGmax",
  "tyranitar-mega": "megaGmax",
  "blaziken-mega": "megaGmax",
  "gardevoir-mega": "megaGmax",
  "mawile-mega": "megaGmax",
  "aggron-mega": "megaGmax",
  "medicham-mega": "megaGmax",
  "manectric-mega": "megaGmax",
  "banette-mega": "megaGmax",
  "absol-mega": "megaGmax",
  "garchomp-mega": "megaGmax",
  "lucario-mega": "megaGmax",
  "abomasnow-mega": "megaGmax",
  "latias-mega": "megaGmax",
  "latios-mega": "megaGmax",
  "swampert-mega": "megaGmax",
  "sceptile-mega": "megaGmax",
  "sableye-mega": "megaGmax",
  "altaria-mega": "megaGmax",
  "gallade-mega": "megaGmax",
  "audino-mega": "megaGmax",
  "sharpedo-mega": "megaGmax",
  "slowbro-mega": "megaGmax",
  "steelix-mega": "megaGmax",
  "pidgeot-mega": "megaGmax",
  "glalie-mega": "megaGmax",
  "diancie-mega": "megaGmax",
  "metagross-mega": "megaGmax",
  "rayquaza-mega": "megaGmax",
  "camerupt-mega": "megaGmax",
  "lopunny-mega": "megaGmax",
  "salamence-mega": "megaGmax",
  "beedrill-mega": "megaGmax",
  "eternatus-eternamax": "megaGmax",

  // Gigantamax forms
  "venusaur-gmax": "megaGmax",
  "charizard-gmax": "megaGmax",
  "blastoise-gmax": "megaGmax",
  "butterfree-gmax": "megaGmax",
  "pikachu-gmax": "megaGmax",
  "meowth-gmax": "megaGmax",
  "machamp-gmax": "megaGmax",
  "gengar-gmax": "megaGmax",
  "kingler-gmax": "megaGmax",
  "lapras-gmax": "megaGmax",
  "eevee-gmax": "megaGmax",
  "snorlax-gmax": "megaGmax",
  "garbodor-gmax": "megaGmax",
  "melmetal-gmax": "megaGmax",
  "rillaboom-gmax": "megaGmax",
  "cinderace-gmax": "megaGmax",
  "inteleon-gmax": "megaGmax",
  "corviknight-gmax": "megaGmax",
  "orbeetle-gmax": "megaGmax",
  "drednaw-gmax": "megaGmax",
  "coalossal-gmax": "megaGmax",
  "flapple-gmax": "megaGmax",
  "appletun-gmax": "megaGmax",
  "sandaconda-gmax": "megaGmax",
  "toxtricity-amped-gmax": "megaGmax",
  "toxtricity-low-key-gmax": "megaGmax",
  "centiskorch-gmax": "megaGmax",
  "hatterene-gmax": "megaGmax",
  "grimmsnarl-gmax": "megaGmax",
  "alcremie-gmax": "megaGmax",
  "copperajah-gmax": "megaGmax",
  "duraludon-gmax": "megaGmax",
  "urshifu-single-strike-gmax": "megaGmax",
  "urshifu-rapid-strike-gmax": "megaGmax",

  // Origin/Primal forms
  "kyogre-primal": "originPrimal",
  "groudon-primal": "originPrimal",
  "giratina-origin": "originPrimal",
  "dialga-origin": "originPrimal",
  "palkia-origin": "originPrimal"
};
