
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irgivbujlgezbxosxqgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyZ2l2YnVqbGdlemJ4b3N4cWdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1Njg0ODgsImV4cCI6MjA2NDE0NDQ4OH0.KFBQazOEgvy4Q14OHpHLve12brZG7Rgaf_CypY74zrs";

console.log('🔥🔥🔥 SUPABASE_CLIENT: ===== CREATING SINGLETON SUPABASE CLIENT =====');
console.log('🔥🔥🔥 SUPABASE_CLIENT: URL:', SUPABASE_URL);
console.log('🔥🔥🔥 SUPABASE_CLIENT: Creating client with explicit config');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

console.log('🔥🔥🔥 SUPABASE_CLIENT: ✅ SINGLETON CLIENT CREATED SUCCESSFULLY ✅');
console.log('🔥🔥🔥 SUPABASE_CLIENT: Client instance:', supabase);
console.log('🔥🔥🔥 SUPABASE_CLIENT: Timestamp:', new Date().toISOString());

// Store globally for debugging
if (typeof window !== 'undefined') {
  (window as any).supabaseClientInstance = supabase;
  (window as any).supabaseClientCreated = new Date().toISOString();
}
